---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.3
    driver:
      network:
        - ["forwarded_port", {guest: 7878, host: 7878}]
  - name: ubuntu-16.04
    driver:
      network:
        - ["forwarded_port", {guest: 7878, host: 17878}]
  - name: ubuntu-14.04
    driver:
      network:
        - ["forwarded_port", {guest: 7878, host: 27878}]

suites:
  - name: default
    run_list:
      - recipe[radarr::default]
